name: Get Branch Name

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  get-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine branch name
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
              echo "BRANCH_NAME=${{ github.event.pull_request.base.ref  }}" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "push" ]]; then
              echo "BRANCH_NAME=${{ github.ref_name  }}" >> $GITHUB_ENV
          else
              echo "Only push and pull_request events are supported"
              exit 1
          fi

      - name: Use branch name
        run: |
          echo "Branch name: $BRANCH_NAME"
